openapi: 3.0.2
info:
  version: 1.0.1
  title: "OCI Database Services Module"
  description: 'Provides an evergreen source for all Oracle Database service information.'
  contact:
    name: DB Expert
    url: https://www.oracle.com/dbexpert
    email: dbexpert_ww_grp@oracle.com
servers:
  - url: https://apexadb.oracle.com/ords/dbexpert/db-services/
tags:
  - name: Service APIs
paths:
  /v1/all:
    get:
      description: >
        Key attributes and characteristics for all Oracle Database cloud services, MySQL Database Service with HeatWave, NoSQL Database Cloud Service, OCI Database with PostgreSQL, and IaaS options for Oracle Database.
        <br/> 
        <br/> 
        See our Database Expert Resources [compare-all](https://apexadb.oracle.com/ords/r/dbexpert/dbsn/compare-all) grid for a human-readable version. 
      tags:
        - Service APIs
      responses:
        '200':
          description: The queried record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /v1/ids:
    get:
      description: List all available OCI Database Service IDs.
      tags:
        - Service APIs
      responses:
        '200':
          description: The queried record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /v1/{id}:
    get:
      description: Retrieve detailed information about a single OCI Database Service via an [ID](#/Service%20APIs/get_v1_ids).
      tags:
        - Service APIs
      responses:
        '200':
          description: The queried record.
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: ^[^/]+$
          description: implicit
